/*
Permission is hereby granted, free of charge, to any person or
organization obtaining a copy of the software and accompanying
documentation covered by this license (the “Software”) to use,
reproduce, display, distribute, execute, and transmit the Software,
and to prepare derivative works of the Software, and to permit
third-parties to whom the Software is furnished to do so, all subject
to the following:

The copyright notices in the Software and this entire statement,
including the above license grant, this restriction and the following
disclaimer, must be included in all copies of the Software, in whole
or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of
machine-executable object code generated by a source language
processor.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#include <stdint.h>

typedef uint64_t msize_t;
typedef uint64_t mkey_t;
#define mvalue_t uint64_t

#include "node_types.h"

typedef leaf_map_node_kv_t leaf_node_t;
typedef internal_node_kc_t internal_node_t;

#define INFIX 8U8U
#define FMT_KEY "%"PRIu64"\n"
#define FMT_KEY_VALUE "key: %" PRIu64 " value: %" PRIu64 "\n"
#define MIN_KEY (mkey_t) 0
#define MAX_KEY (mkey_t) -1

#define NO_SIZE
#define NO_MEMUSED
#define NO_FREE

#include "marika_tmpl.h"
#include "marika_map.h"
#include "impl.i"

uint64_t* mar8U8Uins(void** array, uint64_t index, marika_error_t *err) {
	int new_item;
	return mar8U8Uput(array, index, &new_item, err);
}
