/*
Permission is hereby granted, free of charge, to any person or
organization obtaining a copy of the software and accompanying
documentation covered by this license (the “Software”) to use,
reproduce, display, distribute, execute, and transmit the Software,
and to prepare derivative works of the Software, and to permit
third-parties to whom the Software is furnished to do so, all subject
to the following:

The copyright notices in the Software and this entire statement,
including the above license grant, this restriction and the following
disclaimer, must be included in all copies of the Software, in whole
or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of
machine-executable object code generated by a source language
processor.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#include <stdint.h>

typedef uint32_t msize_t;
typedef int32_t mkey_t;
#define mvalue_t int64_t

#include "node_types.h"

typedef leaf_map_node_vk_t leaf_node_t;
typedef internal_node_ck_t internal_node_t;

#define INFIX 4S8S
#define FMT_KEY "%"PRId32"\n"
#define FMT_KEY_VALUE "key: %" PRId32 " value: %" PRId64 "\n"
#define MIN_KEY (mkey_t) 0x80000000
#define MAX_KEY (mkey_t) 0x7FFFFFFF

#define NO_SEARCH
#define NO_FIRST
#define NO_NEXT
#define NO_LAST
#define NO_PREV
#define NO_INSERT
#define NO_SANITY
#define NO_ITERATE
#define NO_SIZE
#define NO_COUNT
#define NO_MEMUSED
#define NO_FREE
#define NO_ITERATE

#include "marika_tmpl.h"
#include "marika_map.h"
#include "impl.i"
