/*
Permission is hereby granted, free of charge, to any person or
organization obtaining a copy of the software and accompanying
documentation covered by this license (the “Software”) to use,
reproduce, display, distribute, execute, and transmit the Software,
and to prepare derivative works of the Software, and to permit
third-parties to whom the Software is furnished to do so, all subject
to the following:

The copyright notices in the Software and this entire statement,
including the above license grant, this restriction and the following
disclaimer, must be included in all copies of the Software, in whole
or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of
machine-executable object code generated by a source language
processor.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#ifndef _MARIKA_SET_H_
#define _MARIKA_SET_H_

#define CONCAT(a, b, c) a ## b ## c
#define CONCAT_EXPANDED(a, b, c) CONCAT(a, b, c)

#define SANITY CONCAT_EXPANDED(mar, INFIX, sanity)
#define SEARCH CONCAT_EXPANDED(mar, INFIX, test)
#define INSERT CONCAT_EXPANDED(mar, INFIX, set)
#define FIRST CONCAT_EXPANDED(mar, INFIX, first)
#define LAST  CONCAT_EXPANDED(mar, INFIX, last)
#define NEXT  CONCAT_EXPANDED(mar, INFIX, next)
#define PREV  CONCAT_EXPANDED(mar, INFIX, prev)
#define SIZE  CONCAT_EXPANDED(mar, INFIX, size)
#define COUNT CONCAT_EXPANDED(mar, INFIX, count)
#define MEMUSED CONCAT_EXPANDED(mar, INFIX, memused)
#define SET   CONCAT_EXPANDED(mar, INFIX, set)
#define FREE_ARRAY  CONCAT_EXPANDED(mar, INFIX, free)
#define PRINT CONCAT_EXPANDED(mar, INFIX, print)
#define ITERATE CONCAT_EXPANDED(mar, INFIX, iterate)
#define ITERATOR_INIT CONCAT_EXPANDED(mar, INFIX, iterator_init)
#define ITERATOR_DESTROY CONCAT_EXPANDED(mar, INFIX, iterator_destroy)

#endif // _MARIKA_SET_H_
