/*
Permission is hereby granted, free of charge, to any person or
organization obtaining a copy of the software and accompanying
documentation covered by this license (the “Software”) to use,
reproduce, display, distribute, execute, and transmit the Software,
and to prepare derivative works of the Software, and to permit
third-parties to whom the Software is furnished to do so, all subject
to the following:

The copyright notices in the Software and this entire statement,
including the above license grant, this restriction and the following
disclaimer, must be included in all copies of the Software, in whole
or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of
machine-executable object code generated by a source language
processor.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#ifndef __SET_TYPES_H__
#define __SET_TYPES_H__

#ifndef mvalue_t
typedef struct {
	mkey_t keys[NODE_SIZE / sizeof(mkey_t)];
} leaf_set_node_t;
#else
typedef struct {
	// Here we assume that size(mvalue_t) >= sizeof(mkey_t) and therefore
	// place "values" first for better alignment
	mvalue_t values[NODE_SIZE / (sizeof(mkey_t) + sizeof(mvalue_t))];
	mkey_t keys[NODE_SIZE / (sizeof(mkey_t) + sizeof(mvalue_t))];
	uint8_t _[NODE_SIZE % (sizeof(mkey_t) + sizeof(mvalue_t))]; // padding up to NODE_SIZE
} leaf_map_node_vk_t;
typedef struct {
	// Here we assume that sizeof(mkey_t) >= size(mvalue_t) and therefore
	// place "keys" first for better alignment
	mkey_t keys[NODE_SIZE / (sizeof(mkey_t) + sizeof(mvalue_t))];
	mvalue_t values[NODE_SIZE / (sizeof(mkey_t) + sizeof(mvalue_t))];
	uint8_t _[NODE_SIZE % (sizeof(mkey_t) + sizeof(mvalue_t))]; // padding up to NODE_SIZE
} leaf_map_node_kv_t;
#endif

typedef struct {
	// Here we assume that size(void*) >= sizeof(mkey_t) and therefore
	// place "childs" first for better alignment
	void* childs[NODE_SIZE / (sizeof(mkey_t) + sizeof(void*))];
	mkey_t keys[NODE_SIZE / (sizeof(mkey_t) + sizeof(void*)) - 1];
	msize_t size; // for top-node only
	char _[NODE_SIZE % (sizeof(mkey_t) + sizeof(void*))];
} internal_node_ck_t; // childs, then keys

typedef struct {
	// Here we assume that sizeof(mkey_t) >= size(void*) and therefore
	// place "keys" first for better alignment
	mkey_t keys[NODE_SIZE / (sizeof(mkey_t) + sizeof(void*)) - 1];
	msize_t size; // for top-node only
	void* childs[NODE_SIZE / (sizeof(mkey_t) + sizeof(void*))];
	char _[NODE_SIZE % (sizeof(mkey_t) + sizeof(void*))];
} internal_node_kc_t; // keys, then childs

#endif
